# -*- coding: utf-8 -*-
"""Mongodb_assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xISGFLh7hOOAKYmha40NFgRma4wcZLQl
"""

!pip install dnspython
!pip install pymongo[srv]

import pymongo
client = pymongo.MongoClient("mongodb+srv://shiv3009:surya1998@cluster0.rkuw6.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.contact
records=db.details

class contacts():
  def __init__(self):
    self.name=input("Enter your Name :")
    self.number=contacts.number()
    self.email=contacts.gmail()
  
  def number():
    b = input("Enter your 10 digit mobile no:")
    if len(b) == 10:
      pass
    else:
      print("Invalid Mobile Number")
      contacts.number()
  
  def gmail():
    c= input("Enter your E-mail Address:")
    if c.endswith("@gmail.com"):
      pass
    else:
      print("invalid E-mail address")
      contacts.gmail()
d=contacts()
records.insert_one(d.__dict__)

